# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Prepare the build environment
        run: |
          cd ~
          sudo apt install git aria2 -y
          git clone https://gitlab.com/OrangeFox/misc/scripts
          cd ~/scripts
          sudo bash setup/android_build_env.sh
          cd $(pwd)
          cd ~/scripts
          sudo bash setup/install_android_sdk.sh

      # Runs a set of commands using the runners shell
      - name: Sync OrangeFox sources using a minimal manifest
        run: |
          mkdir ~/OrangeFox_sync
          cd ~/OrangeFox_sync
          git clone https://gitlab.com/OrangeFox/sync.git (or, using ssh, "git clone git@gitlab.com:OrangeFox/sync.git")
          cd ~/OrangeFox_sync/sync/
          ./orangefox_sync.sh --branch 11.0 --path ~/fox_11.0
      - name: Place trees and kernel
        run: |
          cd ~/OrangeFox_sync
          git clone https://github.com/TeamWin/android_device_xiaomi_natrium device/xiaomi/natrium
      - name: Build it
        run: |
          cd ~/OrangeFox
          source build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
          export LC_ALL="C"
          lunch twrp_<device>-eng && mka recoveryimage
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          # Artifact name
          name: artifact # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: /fdfsf
          # The desired behavior if no files are found using the provided path.
      #Available Options:
        #warn: Output a warning but do not fail the action
        #error: Fail the action with an error message
        #ignore: Do not output any warnings or errors, the action does not fail

        #if-no-files-found: # optional, default is warn
        # Duration after which artifact will expire in days. 0 means using default retention. Minimum 1 day. Maximum 90 days unless changed from the repository settings page.

        #retention-days: # optional
